image: golang:1.13

stages:
  - test
  - build

unit_tests:
  stage: test
  script:
    - make test

vet:
  stage: test
  script:
    - make vet

acceptance_tests:
  stage: test
  retry: 1
  variables:
    TF_LOG: DEBUG
  script:
    # Note: this uses GRIDSCALE_URL, GRIDSCALE_UUID, GRIDSCALE_TOKEN variables
    # defined under Settings → CI/CD → Variables
    - make testacc

build:
  stage: build
  script:
    - make
