name: Go

on:
  push:
    branches: [ master, testGHA ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Prepare GPG key
      env:
        GPG_SECRET: ${{ secrets.GPG_SECRET }}
      run: |
        touch ~/secret.gpg && echo $GPG_SECRET > ~/secret.gpg
        gpg --batch --import ~/secret.gpg
        touch ~/.gnupg/gpg-agent.conf && echo -e "default-cache-ttl 7200\nmax-cache-ttl 31536000\nallow-preset-passphrase" ~/.gnupg/gpg-agent.conf

    - name: Prepare GPG passphrase
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_EMAIL: ${{ secrets.GPG_EMAIL }}
      run: |
        gpg --pinentry-mode=loopback --passphrase $GPG_PASSPHRASE --armor --detach-sign --local-user "${GPG_EMAIL}" README.md
        rm -f README.md.asc