name: Go

on:
  push:
    branches: [ master, testGHA ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create gpg secret key file from env var
      run: touch secret.gpg && echo $GPG_SECRET > secret.gpg && cat secret.gpg
    
    - name: Check if gpg version
      run: gpg --version